title: Chathuranga De Silva
logo: /assets/img/photo_github.jpg
#description: text below the image
show_downloads: true
theme: jekyll-theme-Minimal
#other themes - Architect, Cayman, Dinky, Hacker, Leap day, Merlot, Midnight, Minima, Minimal, Modernist, Slate, Tactile, Time machine
#other themes site - https://pages.github.com/themes/
