title: Chathuranga De Silva
logo: /assets/img/photo_github.jpg
#description: text below the image
show_downloads: true
theme: jekyll-theme-minimal
#other themes - Architect, Cayman, Dinky, Hacker, Leap day, Merlot, Midnight, Minima, minimal, Modenist, Slate, Tactile, Time machine
