title: Chathuranga De Silva
logo: /assets/img/photo_github3.jpg
description: Passionate programmer on an exciting journey into software engineering, leveraging my background in automation engineering to create innovative solutions, continuously expanding my skills in various programming languages and technologies, and embracing collaboration and teamwork to make a positive impact in the field.
show_downloads: false
theme: jekyll-theme-Minimal
#other themes - Architect, Cayman, Dinky, Hacker, Leap day, Merlot, Midnight, Minima, Minimal, Modernist, Slate, Tactile, Time machine
#other themes site - https://pages.github.com/themes/
